## Practicando con Python y SQL


1. Importar las librerías necesarias para crear la conexión y trabajar con Pandas.

In [62]:
import pandas as pd
import mysql.connector
from mysql.connector import Error

2. Crear la conexión a la base de datos Northwind que devuelva un mensaje de error si algo no ocurre cómo debería.

In [63]:
try:
    connection = mysql.connector.connect(
        host='localhost',
        database='northwind',
        user='root',
        password='AlumnaAdalab'
    )
    if connection.is_connected():
        print("Conexión exitosa a la base de datos")
except Error as e:
    print(f"Error al conectar a la base de datos: {e}")

Conexión exitosa a la base de datos

   3. Usando "information_schema" en la conexión a base de datos, extraer los nombres de las columnas de la tabla "customers" de la bases de datos "northwind".

In [64]:
cursor = connection.cursor()
query ='SELECT column_name FROM information_schema.columns WHERE table_name = "customers" AND table_schema = "northwind";'
cursor.execute(query)

resultsAll = cursor.fetchall()
print("Fetch All:", resultsAll)

Fetch All: [('Address',), ('City',), ('CompanyName',), ('ContactName',), ('ContactTitle',), ('Country',), ('CustomerID',), ('Fax',), ('Phone',), ('PostalCode',), ('Region',)]

4. Seleccionar todo de la tabla "customers" donde "city" sea "London" o "Seattle". Almacenar los resultados en una variable.

In [65]:
query = 'SELECT * FROM customers WHERE city = "London" OR city = "Seattle";'
cursor.execute(query)
resultsCity = cursor.fetchall()
print("Fetch All City:", resultsCity)

Fetch All City: [('AROUT', 'Around the Horn', 'Thomas Hardy', 'Sales Representative', '120 Hanover Sq.', 'London', None, 'WA1 1DP', 'UK', '(171) 555-7788', '(171) 555-6750'), ('BSBEV', "B's Beverages", 'Victoria Ashworth', 'Sales Representative', 'Fauntleroy Circus', 'London', None, 'EC2 5NT', 'UK', '(171) 555-1212', None), ('CONSH', 'Consolidated Holdings', 'Elizabeth Brown', 'Sales Representative', 'Berkeley Gardens 12  Brewery', 'London', None, 'WX1 6LT', 'UK', '(171) 555-2282', '(171) 555-9199'), ('EASTC', 'Eastern Connection', 'Ann Devon', 'Sales Agent', '35 King George', 'London', None, 'WX3 6FW', 'UK', '(171) 555-0297', '(171) 555-3373'), ('NORTS', 'North/South', 'Simon Crowther', 'Sales Associate', 'South House 300 Queensbridge', 'London', None, 'SW7 1RZ', 'UK', '(171) 555-7733', '(171) 555-2530'), ('SEVES', 'Seven Seas Imports', 'Hari Kumar', 'Sales Manager', '90 Wadhurst Rd.', 'London', None, 'OX15 4NB', 'UK', '(171) 555-1717', '(171) 555-5646'), ('WHITC', 'White Clover Markets', 'Karl Jablonski', 'Owner', '305 - 14th Ave. S. Suite 3B', 'Seattle', 'WA', '98128', 'USA', '(206) 555-4112', '(206) 555-4115')]

5. Convertir los resultados del ejercicio anterior en un Dataframe (no olvidéis de poner el nombre a las columnas en el orden correcto).

In [67]:
resultsCity_df = pd.DataFrame(resultsCity, columns=[col[0] for col in resultsAll])
print(resultsCity_df)

  Address                   City        CompanyName           ContactName  \
0   AROUT        Around the Horn       Thomas Hardy  Sales Representative
1   BSBEV          B's Beverages  Victoria Ashworth  Sales Representative
2   CONSH  Consolidated Holdings    Elizabeth Brown  Sales Representative
3   EASTC     Eastern Connection          Ann Devon           Sales Agent
4   NORTS            North/South     Simon Crowther       Sales Associate
5   SEVES     Seven Seas Imports         Hari Kumar         Sales Manager
6   WHITC   White Clover Markets     Karl Jablonski                 Owner

                   ContactTitle  Country CustomerID       Fax Phone  \
0               120 Hanover Sq.   London       None   WA1 1DP    UK
1             Fauntleroy Circus   London       None   EC2 5NT    UK
2  Berkeley Gardens 12  Brewery   London       None   WX1 6LT    UK
3                35 King George   London       None   WX3 6FW    UK
4  South House 300 Queensbridge   London       None   SW7 1RZ    UK
5               90 Wadhurst Rd.   London       None  OX15 4NB    UK
6   305 - 14th Ave. S. Suite 3B  Seattle         WA     98128   USA

       PostalCode          Region
0  (171) 555-7788  (171) 555-6750
1  (171) 555-1212            None
2  (171) 555-2282  (171) 555-9199
3  (171) 555-0297  (171) 555-3373
4  (171) 555-7733  (171) 555-2530
5  (171) 555-1717  (171) 555-5646
6  (206) 555-4112  (206) 555-4115

6. Muestra las 10 primeras filas del Dataframe y las 10 últimas.

In [70]:
resultsCity_df.head(10)

,Address,City,CompanyName,ContactName,ContactTitle,Country,CustomerID,Fax,Phone,PostalCode,Region
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,None,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
1,BSBEV,B's Beverages,Victoria Ashworth,Sales Representative,Fauntleroy Circus,London,None,EC2 5NT,UK,(171) 555-1212,None
2,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,None,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,None,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,None,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
5,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,None,OX15 4NB,UK,(171) 555-1717,(171) 555-5646
6,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115

In [71]:
resultsCity_df.tail(10)

,Address,City,CompanyName,ContactName,ContactTitle,Country,CustomerID,Fax,Phone,PostalCode,Region
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,None,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
1,BSBEV,B's Beverages,Victoria Ashworth,Sales Representative,Fauntleroy Circus,London,None,EC2 5NT,UK,(171) 555-1212,None
2,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,None,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,None,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,None,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
5,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,None,OX15 4NB,UK,(171) 555-1717,(171) 555-5646
6,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115

7. Mostrar 5 filas aleatorias del Dataframe.

In [73]:
resultsCity_df.sample(5)

,Address,City,CompanyName,ContactName,ContactTitle,Country,CustomerID,Fax,Phone,PostalCode,Region
2,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,None,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
6,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,None,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,None,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,None,WX3 6FW,UK,(171) 555-0297,(171) 555-3373

8. ¿Hay nulos en el Dataframe? El resultado debe verse para cada una de las columnas.

In [74]:
resultsCity_df.isnull().sum()

Address         0
City            0
CompanyName     0
ContactName     0
ContactTitle    0
Country         0
CustomerID      6
Fax             0
Phone           0
PostalCode      0
Region          1
dtype: int64

9. Mostrar los principales estadísticos.

In [75]:
resultsCity_df.describe()

,Address,City,CompanyName,ContactName,ContactTitle,Country,CustomerID,Fax,Phone,PostalCode,Region
count,7,7,7,7,7,7,1,7,7,7,6
unique,7,7,7,5,7,2,1,7,2,7,6
top,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,WA,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
freq,1,1,1,3,1,6,1,1,6,1,1

10. Mostrar el nombre de las columnas del Dataframe.

In [76]:
resultsCity_df.columns

Index(['Address', 'City', 'CompanyName', 'ContactName', 'ContactTitle',
       'Country', 'CustomerID', 'Fax', 'Phone', 'PostalCode', 'Region'],
      dtype='object')